#!/bin/bash

# Function to download plugins from GitHub
function plugin() {
  local repo=$1
  local plugin_dir="${HOME}/.dotfiles/plugins/${repo##*/}"

  if [ ! -d "$plugin_dir" ]; then
    echo "Installing plugin: $repo"
    git clone "https://github.com/$repo.git" "$plugin_dir"
  fi

  chmod g-w -R "$plugin_dir"

  # only run if we are being sourced from zsh
  if [ -n "$ZSH_VERSION" ]; then
    source "$plugin_dir/${repo##*/}.plugin.zsh"
  fi
}

# Create the plugins directory if it doesn't exist
mkdir -p "${HOME}/.dotfiles/plugins"

plugin "zsh-users/zsh-autosuggestions"
plugin "zsh-users/zsh-completions"
plugin "zsh-users/zsh-syntax-highlighting"
plugin "joshskidmore/zsh-fzf-history-search"
plugin "djui/alias-tips"