import { resolveSkills } from "../lib/subagents/options.ts";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getAgentDir, type ExtensionAPI, type ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { loadDefinitions, resolveModel, EFFORTS, type AgentEffort } from "../lib/subagents/definitions.ts";
import { VisibleChild } from "../lib/subagents/visible.ts";
import { getSubagentRuntime } from "../lib/subagents/runtime.ts";
const Surface=Type.Union([Type.Literal("headless"),Type.Literal("visible")]);
const Effort=Type.Union(EFFORTS.map(x=>Type.Literal(x)) as any);
function output(value:unknown,error=false){return{content:[{type:"text" as const,text:JSON.stringify(value,null,2)}],details:value,isError:error}}
export default function subagents(pi:ExtensionAPI){
 if(process.env.PI_SUBAGENT_AUTHORITY)return;
 const runtime=getSubagentRuntime(),profile=resolve(getAgentDir()),childExt=join(dirname(fileURLToPath(import.meta.url)),"subagent-child.ts");let origin="",catalog=loadDefinitions(process.cwd(),false);let current:ExtensionContext|undefined;
 const deliver=(r:any)=>{if(r.origin!==origin||!current||current.sessionManager.getSessionId()!==origin||!current.isIdle())return false;pi.sendMessage({customType:"subagent-result",details:{deliveryId:r.deliveryId,origin:r.origin},content:`Subagent ${r.agent} (${r.id}) ${r.status==="waiting"?"asks a factual question":r.outcome}:\n${r.result||r.error||"No result"}`,display:true},{triggerTurn:true,deliverAs:"followUp"});return true};const binding={deliver};
 pi.on("session_start",(_e,ctx)=>{current=ctx;origin=ctx.sessionManager.getSessionId();catalog=loadDefinitions(ctx.cwd,ctx.isProjectTrusted());runtime.bind(origin,binding)});
 pi.on("session_shutdown",async(e)=>{runtime.unbind(origin,binding);current=undefined;if(e.reason==="quit")await runtime.shutdown("quit")});
 pi.on("message_end",(event,ctx)=>{const message=event.message as any;if(message.role==="custom"&&message.customType==="subagent-result"&&message.details?.origin===ctx.sessionManager.getSessionId())runtime.acknowledge(message.details.origin,message.details.deliveryId)});
 pi.on("agent_settled",()=>runtime.flush(origin));
 pi.on("before_agent_start",event=>({systemPrompt:`${event.systemPrompt}\n\nDelegation: use subagent for bounded specialist work. Use a teamlead only when coordination helps. Councils are only on explicit user request. Normally use at most four Team Leads, eight leaves per lead, or twelve direct workers where a lead adds no value. Prefer small jobs that finish relatively quickly. These counts and council structure are guidance, not runtime quotas. Inspect and continue retained conversations with subagent_control.`}));
 pi.registerTool({name:"subagent",label:"Subagent",description:"Launch one defined subagent. Visible is the default in Herdr; headless is the default elsewhere.",parameters:Type.Object({agent:Type.String(),instructions:Type.String(),cwd:Type.Optional(Type.String()),model:Type.Optional(Type.String()),effort:Type.Optional(Effort),skills:Type.Optional(Type.Array(Type.String())),background:Type.Optional(Type.Boolean()),surface:Type.Optional(Surface),retain:Type.Optional(Type.Boolean())}),async execute(_id,p,_s,_u,ctx){try{catalog=loadDefinitions(ctx.cwd,ctx.isProjectTrusted());const d=catalog.agents.get(p.agent);if(!d)throw new Error(`Unknown or invalid agent ${p.agent}. ${catalog.errors.join("; ")}`);
 const chosen=p.model??d.model;resolveModel(chosen,undefined);const skills=resolveSkills(profile,d.skills,p.skills);const surface=p.surface??(process.env.HERDR_ENV==="1"?"visible":"headless");const r=await runtime.launch({definition:d,instructions:p.instructions,cwd:resolve(ctx.cwd,p.cwd||"."),model:chosen!,effort:(p.effort??d.effort??"low") as AgentEffort,skills,origin,retained:p.retain??false,surface,catalog:catalog.agents},profile,childExt,p.background??false,_s);return output(r)}catch(e){return output({error:e instanceof Error?e.message:String(e)},true)}}});
 pi.registerTool({name:"subagent_control",label:"Subagent control",description:"Inspect, continue, answer, finish, or cancel an owned subagent.",parameters:Type.Object({action:Type.Union([Type.Literal("inspect"),Type.Literal("message"),Type.Literal("answer"),Type.Literal("escalate"),Type.Literal("finish"),Type.Literal("cancel")]),id:Type.Optional(Type.String()),message:Type.Optional(Type.String())}),async execute(_id,p,_s,_u,ctx){try{if(p.action==="inspect")return output(p.id?runtime.get(p.id,origin).snapshot():runtime.list(origin));if(!p.id)throw new Error(`${p.action} requires id`);const c=runtime.get(p.id,origin);if(c.record.userOwned&&p.action!=="escalate")throw new Error("Parent control is suspended during direct user intervention; the user can use /subagents cancel");if(p.action==="message"){if(!p.message)throw new Error("message requires text");await c.message(p.message)}else if(p.action==="answer"){if(!p.message)throw new Error("answer requires request id and answer");await c.answer(p.message)}else if(p.action==="cancel")await c.cancel();else if(p.action==="finish")await c.finish();else if(p.action==="escalate")await c.escalate(ctx);return output(c.snapshot())}catch(e){return output({error:e instanceof Error?e.message:String(e)},true)}}});
 pi.registerCommand("subagents",{description:"Inspect or cancel subagents",handler:async(args,ctx)=>{const [cmd,id]=args.trim().split(/\s+/);if(cmd==="cancel"&&id)await runtime.get(id,origin).cancel();ctx.ui.notify(JSON.stringify(runtime.list(origin),null,2),"info")}});
 pi.registerCommand("subagent-return",{description:"Return an intervened visible child to parent control",handler:async(args,ctx)=>{const c=runtime.get(args.trim(),origin);if(!(c instanceof VisibleChild))throw new Error("Only visible children have direct user handback");c.handback();ctx.ui.notify(`Returned ${c.record.id} to parent control`,"info")}});
}
