export const integrationTests = [
	"tests/background-terminal-manager.test.ts",
	"tests/background-terminal.test.ts",
	"tests/commit-mutation.test.ts",
	"tests/commit-planning.test.ts",
	"tests/damage-control-replay.test.ts",
	"tests/goal.test.ts",
	"tests/loop-runner.test.ts",
	"tests/loop.test.ts",
	"tests/memory-promote-scan.privacy.test.ts",
	"tests/memory-retrieve.test.ts",
	"tests/memory-snapshot-archive.test.ts",
	"tests/observability.test.ts",
	"tests/operator-status.test.ts",
	"tests/orchestration-stats.test.ts",
	"tests/pi-smoke-runner.test.ts",
	"tests/settings-file.test.ts",
	"tests/structured-edit.test.ts",
	"tests/subagent-tree-runtime.test.ts",
	"tests/subagent-workflow.test.ts",
	"tests/text-edit.test.ts",
	"tests/tool-reduction.test.ts",
	"tests/workflow-commands.test.ts",
] as const;
