# Invoke-WinGetShim.ps1
# Resolves a WinGet-installed binary and invokes it with pass-through arguments.
#
# IMPORTANT: Must be invoked via -Command (not -File) when passing -- separated args,
# because PowerShell's -File mode consumes '--' before the script sees it.
#
#   Correct:   pwsh -NoProfile -Command "& 'path\Invoke-WinGetShim.ps1' -PackageId ID -TargetExe EXE -- --version"
#   Incorrect: pwsh -NoProfile -File path\Invoke-WinGetShim.ps1 -PackageId ID -TargetExe EXE -- --version
#
# .bat shims generated by Install-WinGetShims.ps1 do not use this script â€” they resolve
# the binary inline via Find-WinGetBinary and call it directly to avoid this limitation.

$PackageId    = ""
$TargetExe    = ""
$RelativePath = ""
$passArgs     = @()

$i = 0
while ($i -lt $args.Count) {
    switch ($args[$i]) {
        '-PackageId'    { $i++; $PackageId    = $args[$i] }
        '-TargetExe'    { $i++; $TargetExe    = $args[$i] }
        '-RelativePath' { $i++; $RelativePath = $args[$i] }
        '--'            { $passArgs = if ($i + 1 -lt $args.Count) { @($args[($i + 1)..($args.Count - 1)]) } else { @() }; $i = $args.Count }
        default         { $passArgs += $args[$i] }
    }
    $i++
}

if (-not $PackageId -or -not $TargetExe) {
    Write-Error "Usage: Invoke-WinGetShim.ps1 -PackageId <id> -TargetExe <exe> [-RelativePath <path>] -- [args]"
    exit 1
}

. (Join-Path $PSScriptRoot "Find-WinGetBinary.ps1")

$binaryPath = Find-WinGetBinary -PackageId $PackageId -TargetExe $TargetExe -RelativePath $RelativePath

if (-not $binaryPath) {
    Write-Error "shim: could not resolve $TargetExe -- is $PackageId installed?"
    exit 1
}

& $binaryPath @passArgs
exit $LASTEXITCODE
