minimumReleaseAge: 4320
blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  '@google/genai': false
  koffi: false
  protobufjs: false
  tree-sitter: false
  tree-sitter-bash: false
  tree-sitter-javascript: false
  tree-sitter-powershell: false
  tree-sitter-python: false
  tree-sitter-typescript: false
