onboarding = false

[keys]
previous_tab = "prefix+comma"
next_tab = "prefix+period"

[[keys.command]]
key = "prefix+n"
type = "shell"
command = "pwsh.exe -NoProfile -File \"%USERPROFILE%/.dotfiles/scripts/herdr-new-instance.ps1\""
description = "open a new Pi instance"

[terminal]
default_shell = "C:/Program Files/PowerShell/7/pwsh.exe"

[ui.sidebar.agents.rows_by_agent]
pi = [
    ["state_icon", "agent", "state_text"],
    ["$model", "$context"],
    ["$subagents", "$tasks"],
    ["workspace", "tab"],
]

[ui]
agent_panel_sort = "spaces"
prompt_new_tab_name = false

[update]
channel = "preview"
